### ISSUE TITLE
Crates CI job fails

### ISSUE THREAD

**Issue by bkchr** [paritytech/releng-scripts#31]
See: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2369757

**Comment by joao-paulo-parity** [comment]
I suspected that was a spurious error. That suspicion was confirmed because I retried and the job is passing now.

I don't know yet where the `rm: cannot remove '/builds/parity/mirrors/substrate/.tmp/crates.io/local_uploads/index': Directory not empty` error is coming from precisely, but it should not happen often (it's the first time I'm seeing it).

I'll update here once I have more information.
